theme = "dark_plus"

[editor]
true-color = true
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "total-line-numbers", "file-encoding"]

[keys.normal]
C-s = ":w!"
C-w = ":buffer-close"
";" = "command_mode"
":" = "collapse_selection"

[keys.insert]
C-s = [":w!", "normal_mode"]
C-w = [":buffer-close", "normal_mode"]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "move_line_up"]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after", "move_line_down"]

[keys.normal.C-space]
n = "@:o <C-r>%<C-w>"
x = "@:sh rm <C-r>%"
r = "@:sh mv <C-r>% <C-r>%"
